# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Java Project with Gradle
  
on:
  workflow_call:
    inputs:
      java_version:
        description: 'Specify the Java version'
        required: true
        default: '8'

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # Print the GitHub event context
    - name: Print GitHub Event Context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "GitHub Event Context:"
        echo "$GITHUB_CONTEXT"
      shell: bash

    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test