# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI CD Pipeline for PR
  
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]

jobs:
  build-java:
    uses: ./.github/workflows/build-java.yml
    secrets: inherit
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit
  validation:
    needs: [terraform-plan]
    uses: ./.github/workflows/validation.yml
    secrets: inherit
  auto-approve-merge:
    if: github.event_name == 'pull_request'
    needs: [build-java, terraform-plan, validation]
    uses: ./.github/workflows/auto-approve-merge.yml
    with:
      is_validated: ${{ needs.validation.outputs.is_validated }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit
