name: Run OPA Tests
on: [push]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: OPA Version
      run: opa version

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init
      working-directory: terraform
    
    - name: Terraform Plan
      run: terraform plan -out=tfplan2
      working-directory: terraform

    - name: Terraform Show
      run: terraform show -json tfplan2 > tfplan2.json
      working-directory: terraform



    - name: Run OPA Tests
      run: opa eval --data  tests/terraform.rego --input  terraform/tfplan2.json "data.terraform.analysis.resource_change_summary"